//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Recipe
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Recipe()
    {
        this.Recipe_Dish = new HashSet<Recipe_Dish>();
        this.Recipe_Step = new HashSet<Recipe_Step>();
    }

    public int ID { get; set; }
    public string Name { get; set; }
    public Nullable<System.TimeSpan> Preparation { get; set; }
    public Nullable<System.TimeSpan> Cook { get; set; }
    public Nullable<System.TimeSpan> Rest { get; set; }
    public string Description { get; set; }
    public string Side { get; set; }
    public int Number_Persons { get; set; }
    public int ID_Recipe_Categories { get; set; }

    public virtual Recipe_Categories Recipe_Categories { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Recipe_Dish> Recipe_Dish { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Recipe_Step> Recipe_Step { get; set; }
}
