//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Utensil_Stock
{
    public int Quantity { get; set; }
    public bool Clean { get; set; }
    public int ID_Utensils { get; set; }
    public int ID_Stocks { get; set; }

    public virtual Stock Stock { get; set; }
    public virtual Utensil Utensil { get; set; }
}
