//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EDM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MasterSharpEntities : DbContext
    {
        public MasterSharpEntities()
            : base("name=MasterSharpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Action> Actions { get; set; }
        public virtual DbSet<Dish_Stock> Dish_Stock { get; set; }
        public virtual DbSet<Dish> Dishes { get; set; }
        public virtual DbSet<Food_Stock> Food_Stock { get; set; }
        public virtual DbSet<Food_Types> Food_Types { get; set; }
        public virtual DbSet<Food> Foods { get; set; }
        public virtual DbSet<Recipe_Categories> Recipe_Categories { get; set; }
        public virtual DbSet<Recipe_Dish> Recipe_Dish { get; set; }
        public virtual DbSet<Recipe_Step> Recipe_Step { get; set; }
        public virtual DbSet<Recipe> Recipes { get; set; }
        public virtual DbSet<Size> Sizes { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<Textil_Stock> Textil_Stock { get; set; }
        public virtual DbSet<Textil> Textils { get; set; }
        public virtual DbSet<Utensil_Stock> Utensil_Stock { get; set; }
        public virtual DbSet<Utensil> Utensils { get; set; }
    }
}
