//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe_Dish
    {
        public int Quantity { get; set; }
        public int ID_Dishes { get; set; }
        public int ID_Recipes { get; set; }
    
        public virtual Dish Dish { get; set; }
        public virtual Recipe Recipe { get; set; }
    }
}
