//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterSharp.Model.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe_Step
    {
        public int Food_Quantity { get; set; }
        public int Number_Step { get; set; }
        public int ID_Foods { get; set; }
        public int ID_Recipes { get; set; }
        public int ID_Actions { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual Food Food { get; set; }
        public virtual Recipe Recipe { get; set; }
    }
}
